### 1. Split this string

In [1]:
s="Hi there Same!"

In [2]:
print(s.split())

['Hi', 'there', 'Same!']


### 2.Use.format()to print following string

In [3]:
Output:the diameter of is Earth is 12742 Kilometers.

In [9]:
import numpy as np
import string

In [11]:
plant="Earth"

In [12]:
Kilometer="12742"

In [13]:
print("The diameter of the {} is {} Kilometer:".format(plant,Kilometer))

The diameter of the Earth is 12742 Kilometer:


### 3.Next dictonary grap the word "hello"

In [14]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [15]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


### 4.create array of 10 zeroes


In [16]:
import numpy as np

In [17]:
var=np.zeros(10)

In [18]:
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4.1 create array of 10 fives

In [21]:
import numpy as np

In [26]:
var=np.ones(10)*5

In [27]:
var

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [24]:
array=np.one(10)*5

In [25]:
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### 5.array of all the even integer from 20 to 35

In [28]:
import numpy as np

In [29]:
array=np.arange(20,35,2)

In [30]:
print("array of all the even integer 20 to 35")

array of all the even integer 20 to 35


In [31]:
print(array)

[20 22 24 26 28 30 32 34]


###  6. 3*3 matrix value ranging from 0 to 8

In [32]:
import numpy as np

In [43]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 7.concadinate a and b

In [44]:
import numpy as np

In [49]:
a=np.array([1,2,3])
b=np.array([4,5,6])
resultlist=[]
for i,j in zip(a,b):
    resultlist.append(i+j)
    print(resultlist)

[5]
[5, 7]
[5, 7, 9]


In [50]:
import numpy as np  
x=np.array([[1,2,3]]) 
y=np.array([[4,5,6]])  
z=np.concatenate((x,y), axis=None)  
z  

array([1, 2, 3, 4, 5, 6])

In [51]:
z.ndim

1

### 8. create data form 3 rows and 2 columns 

In [52]:
import pandas as pd

In [53]:
data={'Name':['Afsal','Krish','Hari','Kevin'],'Age':[21,20,22,23],'Address':['Dharmapuri','Banglore','Pommudi','Salem'],'Qualification':['BE','Tech','Software','Enginner']}


In [54]:
df=pd.DataFrame(data)

In [57]:
df.loc[0:3,['Name','Qualification']]

Name Qualification
0  Afsal            BE
1  Krish          Tech
2   Hari      Software
3  Kevin      Enginner

In [59]:
df.loc[0:3,['Name','Qualification','Age','Address']]

Name Qualification  Age     Address
0  Afsal            BE   21  Dharmapuri
1  Krish          Tech   20    Banglore
2   Hari      Software   22     Pommudi
3  Kevin      Enginner   23       Salem

### 9. series  data form 1 st jan 2023 and 10 th Feb 2023

In [80]:
import numpy as np 
import datetime
import pandas as pd
test_date = datetime.datetime.strptime("01-1-2023", "%d-%m-%Y")
test_date = datetime.datetime.strptime("10-2-2023", "%d-%m-%Y")
K = 31
L = 30
date_generated = pd.date_range(test_date, periods=K)
date_generated = pd.date_range(test_date, periods=L)
print(date_generated.strftime("%d-%m-%Y"))
print(date_generated.strftime("%d-%m-%Y"))
np.concatenate(("%d-%m-%Y"), axis=None) 

Index(['10-02-2023', '11-02-2023', '12-02-2023', '13-02-2023', '14-02-2023',
       '15-02-2023', '16-02-2023', '17-02-2023', '18-02-2023', '19-02-2023',
       '20-02-2023', '21-02-2023', '22-02-2023', '23-02-2023', '24-02-2023',
       '25-02-2023', '26-02-2023', '27-02-2023', '28-02-2023', '01-03-2023',
       '02-03-2023', '03-03-2023', '04-03-2023', '05-03-2023', '06-03-2023',
       '07-03-2023', '08-03-2023', '09-03-2023', '10-03-2023', '11-03-2023'],
      dtype='object')
Index(['10-02-2023', '11-02-2023', '12-02-2023', '13-02-2023', '14-02-2023',
       '15-02-2023', '16-02-2023', '17-02-2023', '18-02-2023', '19-02-2023',
       '20-02-2023', '21-02-2023', '22-02-2023', '23-02-2023', '24-02-2023',
       '25-02-2023', '26-02-2023', '27-02-2023', '28-02-2023', '01-03-2023',
       '02-03-2023', '03-03-2023', '04-03-2023', '05-03-2023', '06-03-2023',
       '07-03-2023', '08-03-2023', '09-03-2023', '10-03-2023', '11-03-2023'],
      dtype='object')


array(['%', 'd', '-', '%', 'm', '-', '%', 'Y'], dtype='<U1')

In [76]:
np.concatenate((K,L), axis=None) 

array([31, 30])

### 10. create 2D list Data Frame

In [87]:
import pandas as pd  
a=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df = pd.DataFrame(a, columns =['RollNo', 'Name', 'Age'],
                                           dtype = int) 
print(df)   

   RollNo Name  Age
0       1  aaa   22
1       2  bbb   25
2       3  ccc   24


In [85]:
import warnings
warnings.filterwarnings("ignore")

In [86]:
print(df) 

   RollNo Name   Age
0     1.0  aaa  22.0
1     2.0  bbb  25.0
2     3.0  ccc  24.0
